[2025-07-25T03:23:57.942+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T03:23:57.970+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_data_pipeline.generate_banking_data_2 scheduled__2025-07-24T00:00:00+00:00 [queued]>
[2025-07-25T03:23:57.975+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_data_pipeline.generate_banking_data_2 scheduled__2025-07-24T00:00:00+00:00 [queued]>
[2025-07-25T03:23:57.976+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-25T03:23:57.985+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_banking_data_2> on 2025-07-24 00:00:00+00:00
[2025-07-25T03:23:57.990+0000] {standard_task_runner.py:63} INFO - Started process 279 to run task
[2025-07-25T03:23:57.994+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bank_data_pipeline', 'generate_banking_data_2', 'scheduled__2025-07-24T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/bank_data_pipeline.py', '--cfg-path', '/tmp/tmpmgc54j1n']
[2025-07-25T03:23:57.996+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask generate_banking_data_2
[2025-07-25T03:23:58.010+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-25T03:23:58.040+0000] {task_command.py:426} INFO - Running <TaskInstance: bank_data_pipeline.generate_banking_data_2 scheduled__2025-07-24T00:00:00+00:00 [running]> on host e85c0090af14
[2025-07-25T03:23:58.152+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineering_team_2' AIRFLOW_CTX_DAG_ID='bank_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_banking_data_2' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T00:00:00+00:00'
[2025-07-25T03:23:58.153+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T03:23:58.178+0000] {bank_data_pipeline.py:71} INFO - Starting data generation for run scheduled__2025-07-24T00:00:00+00:00
[2025-07-25T03:23:58.179+0000] {bank_data_pipeline.py:108} ERROR - Unexpected error in data generation: expected str, bytes or os.PathLike object, not NoneType - expected str, bytes or os.PathLike object, not NoneType
[2025-07-25T03:23:58.179+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T03:23:58.180+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bank_data_pipeline.py", line 80, in generate_banking_data
    result = subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1796, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType
[2025-07-25T03:23:58.190+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=bank_data_pipeline, task_id=generate_banking_data_2, run_id=scheduled__2025-07-24T00:00:00+00:00, execution_date=20250724T000000, start_date=20250725T032357, end_date=20250725T032358
[2025-07-25T03:23:58.202+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task generate_banking_data_2 (expected str, bytes or os.PathLike object, not NoneType; 279)
[2025-07-25T03:23:58.249+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-25T03:23:58.270+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T03:23:58.271+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-07-25T03:51:58.243+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-25T03:51:58.273+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_data_pipeline.generate_banking_data_2 scheduled__2025-07-24T00:00:00+00:00 [queued]>
[2025-07-25T03:51:58.279+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_data_pipeline.generate_banking_data_2 scheduled__2025-07-24T00:00:00+00:00 [queued]>
[2025-07-25T03:51:58.279+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-25T03:51:58.288+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): generate_banking_data_2> on 2025-07-24 00:00:00+00:00
[2025-07-25T03:51:58.294+0000] {standard_task_runner.py:63} INFO - Started process 339 to run task
[2025-07-25T03:51:58.297+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bank_data_pipeline', 'generate_banking_data_2', 'scheduled__2025-07-24T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/bank_data_pipeline.py', '--cfg-path', '/tmp/tmpdvcfmhnu']
[2025-07-25T03:51:58.299+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask generate_banking_data_2
[2025-07-25T03:51:58.313+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-25T03:51:58.348+0000] {task_command.py:426} INFO - Running <TaskInstance: bank_data_pipeline.generate_banking_data_2 scheduled__2025-07-24T00:00:00+00:00 [running]> on host f91aa71dc96e
[2025-07-25T03:51:58.458+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineering_team_2' AIRFLOW_CTX_DAG_ID='bank_data_pipeline' AIRFLOW_CTX_TASK_ID='generate_banking_data_2' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-24T00:00:00+00:00'
[2025-07-25T03:51:58.459+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-25T03:51:58.481+0000] {bank_data_pipeline.py:71} INFO - Starting data generation for run scheduled__2025-07-24T00:00:00+00:00
[2025-07-25T03:51:59.073+0000] {bank_data_pipeline.py:88} INFO - Data generation output: 
[2025-07-25T03:51:59.074+0000] {bank_data_pipeline.py:95} INFO - Task completed successfully
[2025-07-25T03:51:59.088+0000] {python.py:237} INFO - Done. Returned value was: {'status': 'success', 'path': '/tmp/generated_data/run_scheduled__2025-07-24T00_00_00+00_00'}
[2025-07-25T03:51:59.088+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-25T03:51:59.106+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=bank_data_pipeline, task_id=generate_banking_data_2, run_id=scheduled__2025-07-24T00:00:00+00:00, execution_date=20250724T000000, start_date=20250725T035158, end_date=20250725T035159
[2025-07-25T03:51:59.154+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-25T03:51:59.191+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-25T03:51:59.195+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
