[2025-07-16T15:23:32.922+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-16T15:23:32.975+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bank_data_pipeline.init_logging_tables manual__2025-07-16T15:19:01.457315+00:00 [queued]>
[2025-07-16T15:23:32.986+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bank_data_pipeline.init_logging_tables manual__2025-07-16T15:19:01.457315+00:00 [queued]>
[2025-07-16T15:23:32.987+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-07-16T15:23:33.003+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): init_logging_tables> on 2025-07-16 15:19:01.457315+00:00
[2025-07-16T15:23:33.014+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=510) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-16T15:23:33.015+0000] {standard_task_runner.py:63} INFO - Started process 511 to run task
[2025-07-16T15:23:33.014+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bank_data_pipeline', 'init_logging_tables', 'manual__2025-07-16T15:19:01.457315+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/bank_data_pipeline.py', '--cfg-path', '/tmp/tmphzpieu2m']
[2025-07-16T15:23:33.016+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask init_logging_tables
[2025-07-16T15:23:33.049+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-16T15:23:33.109+0000] {task_command.py:426} INFO - Running <TaskInstance: bank_data_pipeline.init_logging_tables manual__2025-07-16T15:19:01.457315+00:00 [running]> on host 4c2c441a4888
[2025-07-16T15:23:33.177+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'init_logging_tables', field 'sql'. Template: '/opt/***/sql/create_log_tables.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/sql/create_log_tables.sql
[2025-07-16T15:23:33.179+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1336, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 204, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: /opt/airflow/sql/create_log_tables.sql
[2025-07-16T15:23:33.195+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=bank_data_pipeline, task_id=init_logging_tables, run_id=manual__2025-07-16T15:19:01.457315+00:00, execution_date=20250716T151901, start_date=20250716T152332, end_date=20250716T152333
[2025-07-16T15:23:33.208+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 6 for task init_logging_tables (/opt/airflow/sql/create_log_tables.sql; 511)
[2025-07-16T15:23:33.229+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-16T15:23:33.257+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-07-16T15:23:33.286+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-16T15:23:33.288+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
